spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job-search
    username: postgres
    password: 12345
#    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  flyway:
    locations: "classpath:db.migration"

    schemas: public
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gcp:
      projectId: "job-search-project-395115"
  servlet:
    multipart:
      max-file-size: 10MB
gcp:
  bucket:
    name: "job-search-bucket"
security:
  jwt:
    secret: 68566D597133743677397A24432646294A404D635166546A576E5A7234753778
#spring:
#  profiles:
#    active: dev
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
##    username: ${env.EMAIL_USERNAME}
##    password: ${env.EMAIL_PASSWORD}
#    username: cavidan.niyazali@gmail.com
#    password: piiiyuykjanptdqk
#    properties:
#      mail:
#       smtp:
#         auth: true
#         starttls:
#           enable: true