spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/job-search
    username: postgres
    password: 12345
#    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  flyway:
    locations: "classpath:db.migration"

    schemas: public
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${env.EMAIL_USERNAME}
#    password: ${env.EMAIL_PASSWORD}
#    username: cavidan.niyazali@gmail.com
#    password: piiiyuykjanptdqk
#    username: "vabiss.test1@gmail.com"
#    password: "uqjgeozovzhrleqx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    gcp:
      projectId: "job-search-project-395115"
  servlet:
    multipart:
      max-file-size: 10MB
gcp:
  bucket:
    name: "job-search-bucket"