spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job-search
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: "classpath:db.migration"

    schemas: public
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
