spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: "classpath:db.migration"
    schemas: public
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    gcp:
      projectId: "job-search-project-395115"
  servlet:
    multipart:
      max-file-size: 10MB
gcp:
  bucket:
    name: "job-search-bucket"